docker:
  registry: docker.localhub.com
# imagePullSecrets:
# - name: docker-secret

deployment:
  replicas: 1
  affinity: {}
  nodeSelector: {}
  tolerations: []
  strategy: {}
  resources: {}

monitoring:
  prometheus:
    enable: false
    scrapeInterval: 60s

services:
  mgmtUi:
    baseUrl: 'http://mgmt-ui:80'
  customerService:
    baseUrl: 'http://customer:8090'
  accountService:
    baseUrl: 'http://account:8080'
  keycloak:
    baseUrl: 'http://192.168.99.100:30666'
