docker:
  registry: docker.localhub.com
# imagePullSecrets:
# - name: docker-secret

deployment:
  replicas: 1
  affinity: {}
  nodeSelector: {}
  tolerations: []
  strategy: {}
  resources: {}

monitoring:
  prometheus:
    enable: false
    scrapeInterval: 60s

security:
  jwt:
    jwkSetUri: 'http://keycloak:8080/auth/realms/webrealm/protocol/openid-connect/certs'

serviceClient:
  customerService:
    baseUrl: 'http://customer:8090'

kube:
  serviceType: ClusterIP
